apiVersion: v1
kind: Service
metadata:
  name: {{ include "radrsyslog.fullname" . }}
  labels:
    app: {{ include "radrsyslog.name" . }}
    chart: {{ include "radrsyslog.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    # - port: {{ .Values.service.port }}
    #   targetPort: udp
    #   protocol: UDP
    #   name: udp  
  selector:
    app: {{ include "radrsyslog.name" . }}
    release: {{ .Release.Name }}
  imagePullSecrets:
  - name: regcred